stty -ixon
HISTSIZE= HISTFILESIZE=

export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/home/vieko/.oh-my-zsh"

ZSH_THEME=""
COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  github
  aws
  npm
  tmux
  pyenv
  archlinux
  common-aliases
  last-working-dir
  zsh-completions
  zsh-autosuggestions
  colored-man-pages
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

autoload -U compinit; compinit
autoload -U promptinit; promptinit

PURE_PROMPT_SYMBOL=⚡
PURE_GIT_UP_ARROW=
PURE_GIT_DOWN_ARROW=

prompt pure

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

source ~/.shortcuts

alias vim="nvim"
alias vi="nvim"

alias dotdrop=~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml
