#!/bin/bash
# opout: "open output": A general handler for opening a file's intended output.
# I find this useful especially running from vim.

filename=$(readlink -f "$1")
ext="${filename##*.}"
filename="${filename%.*}"

case "$ext" in
	html) $TRUEBROWSER --new-window $filename.html & ;;
esac
