config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_dunst:
    dst: ~/.config/dunst
    src: config/dunst
  d_feh:
    dst: ~/.config/feh
    src: config/feh
  d_fontconfig:
    dst: ~/.config/fontconfig
    src: config/fontconfig
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_modprobe.d:
    dst: /etc/modprobe.d
    src: etc/modprobe.d
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  d_rules.d:
    dst: /etc/udev/rules.d
    src: etc/udev/rules.d
  d_scripts:
    dst: ~/.scripts
    src: scripts
  d_slim:
    dst: ~/.config/slim
    src: config/slim
  d_system:
    dst: /etc/systemd/system
    src: etc/systemd/system
  d_wal:
    dst: ~/.config/wal
    src: config/wal
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_hushlogin:
    dst: ~/.hushlogin
    src: hushlogin
  f_mbpfan.conf:
    dst: /etc/mbpfan.conf
    src: etc/mbpfan.conf
  f_shortcuts:
    dst: ~/.shortcuts
    src: shortcuts
  f_vconsole.conf:
    dst: /etc/vconsole.conf
    src: etc/vconsole.conf
  f_wall.jpg:
    dst: ~/.config/wall.jpg
    src: config/wall.jpg
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zlogin:
    dst: ~/.zlogin
    src: zlogin
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  hollowearth:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_zlogin
    - f_zshenv
    - f_zshrc
    - f_hushlogin
    - f_gitignore
    - f_compton.conf
    - d_dunst
    - d_fontconfig
    - d_nvim
    - d_polybar
    - d_wal
    - d_feh
    - d_i3
    - d_ranger
    - f_wall.jpg
    - d_rofi
    - d_slim
    - f_shortcuts
    - d_scripts
    - d_modprobe.d
    - d_system
    - d_rules.d
    - f_mbpfan.conf
    - f_vconsole.conf
  pandemonium:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_zlogin
    - f_zshenv
    - f_zshrc
    - f_hushlogin
    - f_gitignore
    - f_compton.conf
    - d_dunst
    - d_fontconfig
    - d_nvim
    - d_polybar
    - d_wal
    - d_feh
    - d_i3
    - d_ranger
    - f_wall.jpg
    - d_rofi
    - d_slim
    - f_shortcuts
    - d_scripts
