config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_dunst:
    dst: ~/.config/dunst
    src: config/dunst
  d_feh:
    dst: ~/.config/feh
    src: config/feh
  d_fontconfig:
    dst: ~/.config/fontconfig
    src: config/fontconfig
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  d_slim:
    dst: ~/.config/slim
    src: config/slim
  d_src:
    dst: ~/.config/nvim/src
    src: config/nvim/src
  d_wal:
    dst: ~/.config/wal
    src: config/wal
  f_coc-settings.json:
    dst: ~/.config/nvim/coc-settings.json
    src: config/nvim/coc-settings.json
  f_coc.vim:
    dst: ~/.config/nvim/src/coc.vim
    src: config/nvim/src/coc.vim
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_hushlogin:
    dst: ~/.hushlogin
    src: hushlogin
  f_tern-config:
    dst: ~/.tern-config
    src: tern-config
  f_wall.jpg:
    dst: ~/.config/wall.jpg
    src: config/wall.jpg
  f_xdefaults:
    dst: ~/.Xdefaults
    src: Xdefaults
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zlogin:
    dst: ~/.zlogin
    src: zlogin
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  pandemonium:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_zlogin
    - f_zshenv
    - f_zshrc
    - f_xdefaults
    - f_hushlogin
    - f_gitignore
    - f_compton.conf
    - d_dunst
    - d_fontconfig
    - d_nvim
    - d_polybar
    - d_wal
    - d_feh
    - d_i3
    - d_ranger
    - f_wall.jpg
    - d_rofi
    - f_tern-config
    - d_slim
    - f_coc-settings.json
    - d_src
    - f_coc.vim
